server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ebs?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ebs
    password: ebs
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
